AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Whereby Assistant Audio Recorder with Amazon ECS Fargate

Parameters:
    Tag:
        Description: tag name for image
        Type: String
        Default: latest

    ECRRepoStackName:
        Description: Name of an active CloudFormation stack that contains the ECR Repo that will be used in this stack
        Type: String
        Default: whereby-assistant-audio-recorder-base

    DeploymentDatetime:
        Description: Date and time of deployment. Also used to force re-deploy the included ECS task definition whenever 'yarn aws:sam:deploy' is called
        Type: String

Globals:
    Function:
        Timeout: 3
        MemorySize: 128

Resources:
    VPC:
        Type: AWS::Serverless::Application
        Properties:
            Location: ./vpc.yml

    Cluster:
        Type: AWS::ECS::Cluster
        Properties:
            CapacityProviders:
                - FARGATE

    Service:
        Type: AWS::ECS::Service
        Properties:
            ServiceName: "whereby-assistant-audio-recorder"
            Cluster: !Ref Cluster
            LaunchType: FARGATE
            EnableExecuteCommand: true
            HealthCheckGracePeriodSeconds: 30
            NetworkConfiguration:
                AwsvpcConfiguration:
                    AssignPublicIp: ENABLED
                    Subnets: [!GetAtt "VPC.Outputs.PublicSubnet1", !GetAtt VPC.Outputs.PublicSubnet2]
                    SecurityGroups: [!GetAtt VPC.Outputs.SG]
            DeploymentConfiguration:
                MaximumPercent: 200
                MinimumHealthyPercent: 50
            DesiredCount: 2
            TaskDefinition: !Ref "TaskDefinition"
            LoadBalancers:
                - ContainerName: "whereby-assistant-audio-recorder"
                  ContainerPort: 80
                  TargetGroupArn: !GetAtt VPC.Outputs.LB

    TaskDefinition:
        Type: AWS::ECS::TaskDefinition
        Properties:
            Family: WherebyAssistantAudioRecorder
            Cpu: 1024
            Memory: 4096
            NetworkMode: awsvpc
            RequiresCompatibilities:
                - FARGATE
            ExecutionRoleArn: !Ref ECSTaskExecutionRole
            TaskRoleArn: !Ref ECSTaskRole
            RuntimePlatform:
                CpuArchitecture: X86_64
            ContainerDefinitions:
                - Name: whereby-assistant-audio-recorder
                  Cpu: 1024
                  Memory: 4096
                  Image: !Sub
                      - ${RepoUrl}:latest
                      - RepoUrl: !ImportValue "whereby-assistant-audio-recorder-base-RepositoryUri"
                  Environment:
                      - Name: DEPLOYMENT_DATETIME
                        Value: !Ref DeploymentDatetime
                      - Name: WHEREBY_ASSISTANT_KEY
                        Value: !Sub "{{resolve:secretsmanager:${AWS::StackName}_WHEREBY_ASSISTANT_KEY:SecretString}}"
                      - Name: AWS_S3_ACCESS_KEY_ID
                        Value: !Sub "{{resolve:secretsmanager:${AWS::StackName}_AWS_S3_ACCESS_KEY_ID:SecretString}}"
                      - Name: AWS_S3_SECRET_ACCESS_KEY
                        Value: !Sub "{{resolve:secretsmanager:${AWS::StackName}_AWS_S3_SECRET_ACCESS_KEY:SecretString}}"
                      - Name: AWS_S3_REGION
                        Value: !Sub "{{resolve:secretsmanager:${AWS::StackName}_AWS_S3_REGION:SecretString}}"
                      - Name: AWS_S3_BUCKET_NAME
                        Value: !Sub "{{resolve:secretsmanager:${AWS::StackName}_AWS_S3_BUCKET_NAME:SecretString}}"
                  PortMappings:
                      - ContainerPort: 80
                  LogConfiguration:
                      LogDriver: awslogs
                      Options:
                          awslogs-group: !Ref LogGroup
                          awslogs-region: !Ref AWS::Region
                          awslogs-stream-prefix: containerlog

    LogGroup:
        Type: AWS::Logs::LogGroup
        Properties:
            LogGroupName: /wherebyassistantaudiorecorder

    ECSTaskExecutionRole:
        Type: AWS::IAM::Role
        Properties:
            AssumeRolePolicyDocument:
                Statement:
                    - Effect: Allow
                      Principal:
                          Service: [ecs-tasks.amazonaws.com]
                      Action: ["sts:AssumeRole"]
            Path: /
            ManagedPolicyArns:
                - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy

    ECSTaskRole:
        Type: AWS::IAM::Role
        Properties:
            AssumeRolePolicyDocument:
                Statement:
                    - Effect: Allow
                      Principal:
                          Service: [ecs-tasks.amazonaws.com]
                      Action: ["sts:AssumeRole"]
            Path: /

    AutoScaling:
        Type: AWS::Serverless::Application
        Properties:
            Location: ./autoscaling.yml
            Parameters:
                ClusterName: !Ref Cluster
                ServiceName: !GetAtt Service.Name

Outputs:
    ClusterName:
        Description: Amazon ECS Cluster Name
        Value: !Ref Cluster
    ServiceName:
        Description: Amazon ECS Service Name
        Value: !GetAtt Service.Name
    FQDN:
        Description: URL for your application
        Value: !GetAtt VPC.Outputs.PublicLBFQDN
